language: csharp
matrix:
  include:
  - os: linux
    mono: latest
    dotnet: 2.2.300
  - os: windows
    mono: none

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export DOTNET_CLI_TELEMETRY_OPTOUT=1; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install dotnetcore-sdk --version 2.2.301 -y; fi
  - dotnet restore
  - dotnet test
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd Documentation; wget https://github.com/dotnet/docfx/releases/download/v2.43.3/docfx.zip; mkdir docfx; unzip docfx.zip -d docfx; mkdir -p Documentation/_site/docs; mono docfx/docfx.exe -o _site/docs/; fi

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $push_token
  local_dir: Documentation/_site
  repo: Kansattica/Kansattica.github.io
  target-branch: master
  verbose: true
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = "linux" 