language: csharp
mono: none
os:
  - linux
  - windows
dotnet: 2.2.300
script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then wget https://dot.net/v1/dotnet-install.ps1; powershell -NoProfile -ExecutionPolicy unrestricted -File dotnet-install.ps1 -Version 2.2.300 ; fi
  - dotnet restore
  - dotnet test
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install docfx -y  ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then powershell -command "cd Documentation; docfx"; fi

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $push_token
  local_dir: Documentation/_site
  repo: Kansattica/Kansattica.github.io
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = "windows" 