language: csharp
mono: none
matrix:
  include:
    - os: linux
    mono: none
    dotnet: 2.2.300
    - os: windows
    mono: none

pre_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install dotnetcore-sdk --version 2.2.301 -y; fi

script:
  - dotnet restore
  - dotnet test
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install docfx -y  ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then powershell -command "cd Documentation; docfx"; fi

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $push_token
  local_dir: Documentation/_site
  repo: Kansattica/Kansattica.github.io
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = "windows" 